#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "💅 Formatting staged files..."
dart run lint_staged || exit 1

echo "🔍 Running static analysis..."
flutter analyze --fatal-infos || {
  echo "❌ Static analysis failed. Please fix the issues before committing."
  exit 1
}

