#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking project health..."
flutter analyze || {
  echo "❌ Static analysis failed. Please fix the issues before committing."
  exit 1
}

dart run lint_staged
